#!/usr/bin/env bun
// Generate src/web-embed.ts from the built web/dist so `bun build --compile`
// can bake the UI into the single binary. Run after `web:build`. The Makefile
// restores the committed stub after compiling so the source stays clean.
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative, sep } from "node:path";

const ROOT = join(import.meta.dir, "..");
const DIST = join(ROOT, "web", "dist");
const OUT = join(ROOT, "src", "web-embed.ts");

const TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".woff2": "font/woff2",
};

if (!existsSync(DIST)) {
  console.error(`✗ ${DIST} not found — run "bun run web:build" first`);
  process.exit(1);
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const entries = walk(DIST)
  .map((file) => {
    const url = "/" + relative(DIST, file).split(sep).join("/");
    const type = TYPES[extname(file)] ?? "application/octet-stream";
    const base64 = readFileSync(file).toString("base64");
    return `  ${JSON.stringify(url)}: ${JSON.stringify({ type, base64 })},`;
  })
  .join("\n");

const body = `// AUTO-GENERATED by scripts/embed-web.ts — do not edit.
export const WEB_ASSETS: Record<string, { type: string; base64: string }> = {
${entries}
};
`;

writeFileSync(OUT, body);
console.log(`✓ embedded ${walk(DIST).length} web assets → ${relative(ROOT, OUT)}`);
