import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { NotFoundError, PreconditionError } from "./errors";
import {
  canonicalSkillRef,
  collectSelectedSkill,
  jsonFile,
  logicalContentHash,
  type ProjectionFile,
  validateMarketplaceName,
} from "./plugin-projection";
import { lsTreeEntriesAtCommit, showAtCommit } from "./git";
import { assertNoSymlinkAncestors } from "./path-safety";

const ownerSchema = z
  .object({ name: z.string().min(1), email: z.string().min(1).optional() })
  .passthrough();
const sourceMarketplaceSchema = z
  .object({
    name: z.string().min(1),
    displayName: z.string().optional(),
    owner: ownerSchema,
  })
  .passthrough();
const policySchema = z
  .object({
    installation: z
      .enum(["NOT_AVAILABLE", "AVAILABLE", "INSTALLED_BY_DEFAULT"])
      .default("AVAILABLE"),
    authentication: z.enum(["ON_INSTALL", "ON_USE"]).default("ON_INSTALL"),
  })
  .passthrough();
const definitionSchema = z
  .object({
    name: z.string().min(1),
    displayName: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    policy: policySchema.default({
      installation: "AVAILABLE",
      authentication: "ON_INSTALL",
    }),
    skills: z.array(z.string()).min(1),
  })
  .passthrough();

export type CodexMarketplaceSource = z.infer<typeof sourceMarketplaceSchema>;
export type CodexPluginDefinition = z.infer<typeof definitionSchema>;

export interface CodexState {
  marketplace: CodexMarketplaceSource;
  definitions: CodexPluginDefinition[];
}

export function validateCodexStateDocument(state: CodexState): CodexState {
  const marketplace = parseJsonSchema(
    JSON.stringify(state.marketplace),
    sourceMarketplaceSchema,
    "Codex marketplace definition",
  );
  validateMarketplaceName(marketplace.name, "marketplace name", "codex");
  return parseCodexDefinitions(
    "",
    marketplace,
    state.definitions.map((definition) => ({
      name: `${definition.name}.json`,
      raw: JSON.stringify(definition),
    })),
  );
}

export const CODEX_README = `# Generated by Capshelf

Do not edit files under this directory.

Capshelf generates this directory from Codex plugin definitions under
\`codex/plugin-definitions/\` and copies their selected canonical skills from
\`skills/\`.

Capshelf marketplace mutations and skill share/promotion regenerate affected
files automatically. After direct edits or merge-conflict resolution, run:

    capshelf marketplace sync --target codex

Validate the result with:

    capshelf marketplace validate --target codex

Commit the source and generated changes together.

The native Codex catalog at \`.agents/plugins/marketplace.json\` is generated
by the same command and must not be edited manually.
`;

export async function loadCodexState(dataRepo: string): Promise<CodexState> {
  await assertNoSymlinkAncestors(
    dataRepo,
    "codex/plugin-definitions/marketplace.json",
  );
  const root = join(dataRepo, "codex", "plugin-definitions");
  let marketplaceRaw: string;
  try {
    marketplaceRaw = await readFile(join(root, "marketplace.json"), "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    throw new NotFoundError("Codex marketplace is not initialized");
  }
  const marketplace = parseJsonSchema(
    marketplaceRaw,
    sourceMarketplaceSchema,
    "Codex marketplace definition",
  );
  validateMarketplaceName(marketplace.name, "marketplace name", "codex");
  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === "marketplace.json") continue;
    if (!entry.isFile() || !entry.name.endsWith(".json")) {
      throw new PreconditionError(
        `unexpected Codex definition entry "${entry.name}"; expected a regular .json file`,
      );
    }
  }
  return parseCodexDefinitions(
    dataRepo,
    marketplace,
    await Promise.all(
      entries
        .filter((entry) => entry.isFile() && entry.name !== "marketplace.json")
        .map(async (entry) => ({
          name: entry.name,
          raw: await readFile(join(root, entry.name), "utf8"),
        })),
    ),
  );
}

export async function loadCodexStateAtHead(
  dataRepo: string,
): Promise<CodexState> {
  let marketplaceRaw: Buffer;
  try {
    marketplaceRaw = await showAtCommit(
      dataRepo,
      "HEAD",
      "codex/plugin-definitions/marketplace.json",
    );
  } catch {
    throw new NotFoundError("Codex marketplace is not initialized at HEAD");
  }
  const marketplace = parseJsonSchema(
    marketplaceRaw.toString("utf8"),
    sourceMarketplaceSchema,
    "Codex marketplace definition",
  );
  validateMarketplaceName(marketplace.name, "marketplace name", "codex");
  const entries = await lsTreeEntriesAtCommit(
    dataRepo,
    "HEAD",
    "codex/plugin-definitions",
  );
  const definitionEntries = entries.filter(
    (entry) => entry.path !== "codex/plugin-definitions/marketplace.json",
  );
  for (const entry of definitionEntries) {
    if (
      !entry.path.endsWith(".json") ||
      entry.mode === "120000" ||
      entry.type !== "blob"
    ) {
      throw new PreconditionError(
        `unexpected Codex definition entry "${entry.path}"; expected a regular .json file`,
      );
    }
  }
  const definitions = await Promise.all(
    definitionEntries.map(async (entry) => ({
      name: entry.path.slice("codex/plugin-definitions/".length),
      raw: (await showAtCommit(dataRepo, "HEAD", entry.path)).toString("utf8"),
    })),
  );
  return parseCodexDefinitions(dataRepo, marketplace, definitions);
}

function parseCodexDefinitions(
  _dataRepo: string,
  marketplace: CodexMarketplaceSource,
  entries: Array<{ name: string; raw: string }>,
): CodexState {
  const definitions: CodexPluginDefinition[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const definition = parseJsonSchema(entry.raw, definitionSchema, entry.name);
    validateMarketplaceName(definition.name, "plugin name", "codex");
    if (entry.name !== `${definition.name}.json`) {
      throw new PreconditionError(
        `${entry.name} must match plugin name "${definition.name}"`,
      );
    }
    const canonical = definition.skills.map(canonicalSkillRef);
    if (new Set(canonical).size !== canonical.length) {
      throw new PreconditionError(`${entry.name} contains duplicate skills`);
    }
    for (const unsupported of [
      "agents",
      "apps",
      "commands",
      "hooks",
      "mcpServers",
      "npm",
      "source",
      "git-subdir",
    ]) {
      if (unsupported in definition) {
        throw new PreconditionError(
          `${entry.name} uses unsupported Codex component "${unsupported}"`,
        );
      }
    }
    definition.skills = canonical.sort();
    definitions.push(definition);
  }
  const duplicate = definitions.find(
    (definition, index) =>
      definitions.findIndex((other) => other.name === definition.name) !==
      index,
  );
  if (duplicate) {
    throw new PreconditionError(`duplicate Codex plugin "${duplicate.name}"`);
  }
  return { marketplace, definitions };
}

function parseJsonSchema<T extends z.ZodTypeAny>(
  raw: string,
  schema: T,
  label: string,
): z.output<T> {
  let value: unknown;
  try {
    value = JSON.parse(raw);
  } catch (error) {
    throw new PreconditionError(`invalid ${label} JSON: ${String(error)}`);
  }
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new PreconditionError(
      `invalid ${label}: ${result.error.issues.map((i) => i.message).join("; ")}`,
    );
  }
  return result.data;
}

export function findCodexDefinition(
  state: CodexState,
  name: string,
): CodexPluginDefinition {
  const definition = state.definitions.find((entry) => entry.name === name);
  if (!definition) throw new NotFoundError(`Codex plugin "${name}" not found`);
  return definition;
}

export async function buildCodexProjection(
  dataRepo: string,
  state: CodexState,
  options: { fromHead?: boolean; only?: string } = {},
): Promise<ProjectionFile[]> {
  const definitions = state.definitions
    .filter((definition) => !options.only || definition.name === options.only)
    .sort((a, b) => a.name.localeCompare(b.name));
  const files: ProjectionFile[] = [];
  const nativePlugins: unknown[] = [];
  for (const definition of definitions) {
    const selected = await Promise.all(
      definition.skills.map((skill) =>
        collectSelectedSkill(dataRepo, skill, options.fromHead),
      ),
    );
    const pluginFiles = selected.flatMap((skill) =>
      skill.files.map((file) => ({
        ...file,
        path: `skills/${skill.name}/${file.path}`,
      })),
    );
    const metadataWithoutVersion = codexPluginManifest(
      state.marketplace,
      definition,
      "",
    );
    delete (metadataWithoutVersion as { version?: string }).version;
    const hash = logicalContentHash(metadataWithoutVersion, pluginFiles);
    const version = `0.0.0+codex.${hash.slice(0, 12)}`;
    const root = `codex/generated/plugins/${definition.name}`;
    files.push(
      jsonFile(
        `${root}/.codex-plugin/plugin.json`,
        codexPluginManifest(state.marketplace, definition, version),
      ),
      ...pluginFiles.map((file) => ({ ...file, path: `${root}/${file.path}` })),
    );
    nativePlugins.push({
      name: definition.name,
      source: {
        source: "local",
        path: `./codex/generated/plugins/${definition.name}`,
      },
      policy: definition.policy,
      category: definition.category ?? "Productivity",
    });
  }
  const marketplaceName = options.only
    ? `${state.marketplace.name}-${options.only}`
    : state.marketplace.name;
  const displayName = options.only
    ? (definitions[0]?.displayName ?? definitions[0]?.name ?? marketplaceName)
    : state.marketplace.displayName;
  files.push(
    jsonFile(".agents/plugins/marketplace.json", {
      name: marketplaceName,
      ...(displayName && { interface: { displayName } }),
      plugins: nativePlugins,
    }),
    {
      path: "codex/generated/README.md",
      bytes: Buffer.from(CODEX_README),
      executable: false,
    },
  );
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

function codexPluginManifest(
  marketplace: CodexMarketplaceSource,
  definition: CodexPluginDefinition,
  version: string,
): Record<string, unknown> {
  const description =
    definition.description ?? definition.displayName ?? definition.name;
  return {
    name: definition.name,
    version,
    description,
    author: marketplace.owner,
    skills: "./skills/",
    interface: {
      displayName: definition.displayName ?? definition.name,
      shortDescription: description.slice(0, 120),
      longDescription: description,
      developerName: marketplace.owner.name,
      category: definition.category ?? "Productivity",
      capabilities: ["Skills"],
      defaultPrompt: [`Use the ${definition.name} plugin.`],
    },
  };
}

export function codexSourceFiles(state: CodexState): ProjectionFile[] {
  return [
    jsonFile("codex/plugin-definitions/marketplace.json", state.marketplace),
    ...state.definitions.map((definition) =>
      jsonFile(`codex/plugin-definitions/${definition.name}.json`, definition),
    ),
  ].sort((a, b) => a.path.localeCompare(b.path));
}
